
var data = `{
    "ALBERTA":{
       "id":9003,
       "BANFF_CANMORE":{
          "id":1700234
       },
       "CALGARY":{
          "id":1700199
       },
       "EDMONTON_AREA":{
          "id":1700202,
          "EDMONTON":[
             null
          ],
          "ST_ALBERT":[
             null
          ],
          "STRATHCONA_COUNTY":[
             null
          ]
       },
       "FORT_MCMURRAY":{
          "id":1700232
       },
       "GRANDE_PRAIRIE":{
          "id":1700233
       },
       "LETHBRIDGE":{
          "id":1700230
       },
       "LLOYDMINSTER":{
          "id":1700095
       },
       "MEDICINE_HAT":{
          "id":1700231
       },
       "RED_DEER":{
          "id":1700136
       }
    },
    "BRITISH_COLUMBIA":{
       "id":9007,
       "CARIBOO_AREA":{
          "id":1700296,
          "HUNDRED_MILE_HOUSE":[
             null
          ],
          "QUESNEL":[
             null
          ],
          "WILLIAMS_LAKE":[
             null
          ]
       },
       "COMOX_VALLEY_AREA":{
          "id":1700298,
          "CAMPBELL_RIVER":[
             null
          ],
          "COMOX_COURTENAY_CUMBERLAND":[
             null
          ]
       },
       "COWICHAN_VALLEY_DUNCAN":{
          "id":1700300
       },
       "CRANBROOK":{
          "id":1700224
       },
       "FRASER_VALLEY":{
          "id":1700139,
          "ABBOTSFORD":[
             null
          ],
          "CHILLIWACK":[
             null
          ],
          "HOPE_KENT":[
             null
          ],
          "MISSION":[
             null
          ]
       },
       "GREATER_VANCOUVER_AREA":{
          "id":80003,
          "BURNABY_NEW_WESTMINSTER":[
             null
          ],
          "DELTA_SURREY_LANGLEY":[
             null
          ],
          "DOWNTOWN_WEST_END":[
             null
          ],
          "NORTH_SHORE":[
             null
          ],
          "RICHMOND":[
             null
          ],
          "TRICITIES_PITT_MAPLE":[
             null
          ],
          "UBC":[
             null
          ],
          "VANCOUVER":[
             null
          ]
       },
       "KAMLOOPS":{
          "id":1700227
       },
       "KELOWNA":{
          "id":1700228,
          "PENTICTON":[
             null
          ]
       },
       "NANAIMO":{
          "id":1700263
       },
       "NELSON":{
          "id":1700226
       },
       "PEACE_RIVER_AREA":{
          "id":1700295,
          "DAWSON_CREEK":[
             null
          ],
          "FORT_ST_JOHN":[
             null
          ]
       },
       "PORT_ALBERNI_OCEANSIDE":{
          "id":1700299,
          "PARKSVILLE_QUALICUM_BEACH":[
             null
          ],
          "PORT_ALBERNI":[
             null
          ]
       },
       "PORT_HARDY_PORT_MCNEILL":{
          "id":1700301
       },
       "POWELL_RIVER_DISTRICT":{
          "id":1700294
       },
       "PRINCE_GEORGE":{
          "id":1700143
       },
       "REVELSTOKE":{
          "id":1700302
       },
       "SKEENA_BULKLEY_AREA":{
          "id":1700297,
          "BURNS_LAKE":[
             null
          ],
          "HOUSTON":[
             null
          ],
          "KITIMAT":[
             null
          ],
          "PRINCE_RUPERT":[
             null
          ],
          "SMITHERS":[
             null
          ],
          "TERRACE":[
             null
          ],
          "VANDERHOOF":[
             null
          ]
       },
       "SUNSHINE_COAST":{
          "id":1700293
       },
       "VERNON":{
          "id":1700229
       },
       "VICTORIA":{
          "id":1700173
       },
       "WHISTLER":{
          "id":1700100
       }
    },
    "MANITOBA":{
       "id":9006,
       "BRANDON_AREA":{
          "id":1700085,
          "BRANDON":[
             null
          ],
          "PORTAGE_LA_PRAIRIE":[
             null
          ]
       },
       "FLIN_FLON":{
          "id":1700236
       },
       "THOMPSON":{
          "id":1700235
       },
       "WINNIPEG":{
          "id":1700192
       }
    },
    "NEW_BRUNSWICK":{
       "id":9005,
       "BATHURST":{
          "id":1700260
       },
       "EDMUNDSTON":{
          "id":1700261
       },
       "FREDERICTON":{
          "id":1700018
       },
       "MIRAMICHI":{
          "id":1700262
       },
       "MONCTON":{
          "id":1700001
       },
       "SAINT_JOHN":{
          "id":80017
       }
    },
    "NEWFOUNDLAND":{
       "id":9008,
       "CORNER_BROOK":{
          "id":1700254
       },
       "GANDER":{
          "id":1700255
       },
       "LABRADOR":{
          "id":1700044,
          "GOOSE_BAY":[
             null
          ],
          "LABRADOR_CITY":[
             null
          ]
       },
       "ST_JOHNS":{
          "id":1700113
       }
    },
    "NOVA_SCOTIA":{
       "id":9002,
       "ANNAPOLIS_VALLEY":{
          "id":1700256
       },
       "BRIDGEWATER":{
          "id":1700257
       },
       "CAPE_BRETON":{
          "id":1700011
       },
       "HALIFAX":{
          "id":80010,
          "BEDFORD":[
             null
          ],
          "CITY_OF_HALIFAX":[
             null
          ],
          "COLE_HARBOUR":[
             null
          ],
          "DARTMOUTH":[
             null
          ]
       },
       "NEW_GLASGOW":{
          "id":1700258
       },
       "TRURO":{
          "id":1700047
       },
       "YARMOUTH":{
          "id":1700259
       }
    },
    "ONTARIO":{
       "id":9004,
       "BARRIE":{
          "id":1700006
       },
       "BELLEVILLE_AREA":{
          "id":1700129,
          "BELLEVILLE":[
             null
          ],
          "TRENTON":[
             null
          ]
       },
       "BRANTFORD":{
          "id":1700206
       },
       "BROCKVILLE":{
          "id":1700247
       },
       "CHATHAM_KENT":{
          "id":1700239
       },
       "CORNWALL":{
          "id":1700133
       },
       "GUELPH":{
          "id":1700242
       },
       "HAMILTON":{
          "id":80014
       },
       "KAPUSKASING":{
          "id":1700237
       },
       "KENORA":{
          "id":1700249
       },
       "KINGSTON_AREA":{
          "id":1700181,
          "KINGSTON":[
             null
          ],
          "NAPANEE":[
             null
          ]
       },
       "KITCHENER_AREA":{
          "id":1700209,
          "CAMBRIDGE":[
             null
          ],
          "KITCHENER_WATERLOO":[
             null
          ],
          "STRATFORD":[
             null
          ]
       },
       "LEAMINGTON":{
          "id":1700240
       },
       "LONDON":{
          "id":1700214
       },
       "MUSKOKA":{
          "id":1700078
       },
       "NORFOLK_COUNTY":{
          "id":1700248
       },
       "NORTH_BAY":{
          "id":1700243
       },
       "OTTAWA_GATINEAU_AREA":{
          "id":1700184,
          "GATINEAU":[
             null
          ],
          "OTTAWA":[
             null
          ]
       },
       "OWEN_SOUND":{
          "id":1700187
       },
       "PETERBOROUGH_AREA":{
          "id":1700217,
          "KAWARTHA_LAKES":[
             null
          ],
          "PETERBOROUGH":[
             null
          ]
       },
       "RENFREW_COUNTY_AREA":{
          "id":1700074,
          "PEMBROKE":[
             null
          ],
          "PETAWAWA":[
             null
          ],
          "RENFREW":[
             null
          ]
       },
       "SARNIA_AREA":{
          "id":1700189,
          "GRAND_BEND":[
             null
          ],
          "SARNIA":[
             null
          ]
       },
       "SAULT_STE_MARIE":{
          "id":1700244
       },
       "ST_CATHARINES":{
          "id":80016
       },
       "SUDBURY":{
          "id":1700245
       },
       "THUNDER_BAY":{
          "id":1700126
       },
       "TIMMINS":{
          "id":1700238
       },
       "TORONTO_GTA":{
          "id":1700272,
          "CITY_OF_TORONTO":[
             null
          ],
          "MARKHAM_YORK_REGION":[
             null
          ],
          "MISSISSAUGA_PEEL_REGION":[
             null
          ],
          "OAKVILLE_HALTON_REGION":[
             null
          ],
          "OSHAWA_DURHAM_REGION":[
             null
          ]
       },
       "WINDSOR_REGION":{
          "id":1700220
       },
       "WOODSTOCK":{
          "id":1700241
       }
    },
    "PRINCE_EDWARD_ISLAND":{
       "id":9011,
       "PRINCE_EDWARD_ISLAND":{
          "id":1700118,
          "CHARLOTTETOWN":[
             null
          ],
          "SUMMERSIDE":[
             null
          ]
       }
    },
    "QUEBEC":{
       "id":9001,
       "ABITIBI_TEMISCAMINGUE":{
          "id":1700059,
          "ROUYN_NORANDA":[
             null
          ],
          "VAL_DOR":[
             null
          ]
       },
       "BAIE_COMEAU":{
          "id":1700251
       },
       "CENTRE_DU_QUEBEC":{
          "id":1700121,
          "DRUMMONDVILLE":[
             null
          ],
          "VICTORIAVILLE":[
             null
          ]
       },
       "CHAUDIERE_APPALACHES":{
          "id":1700062,
          "LEVIS":[
             null
          ],
          "ST_GEORGES_DE_BEAUCE":[
             null
          ],
          "THETFORD_MINES":[
             null
          ]
       },
       "CHIBOUGAMAU_NORTHERN_QUEBEC":{
          "id":1700284
       },
       "GASPE":{
          "id":1700066
       },
       "GRANBY":{
          "id":1700253
       },
       "GREATER_MONTREAL":{
          "id":80002,
          "CITY_OF_MONTREAL":[
             null
          ],
          "LAVAL_NORTH_SHORE":[
             null
          ],
          "LONGUEUIL_SOUTH_SHORE":[
             null
          ],
          "WEST_ISLAND":[
             null
          ]
       },
       "LANAUDIERE":{
          "id":1700283
       },
       "LAURENTIDES":{
          "id":1700282
       },
       "MAURICIE":{
          "id":1700147,
          "SHAWINIGAN":[
             null
          ],
          "TROIS_RIVIERES":[
             null
          ]
       },
       "QUEBEC_CITY":{
          "id":1700124
       },
       "RIMOUSKI_BAS_ST_LAURENT":{
          "id":1700250
       },
       "SAGUENAY_LAC_SAINT_JEAN":{
          "id":1700178,
          "LAC_SAINT_JEAN":[
             null
          ],
          "SAGUENAY":[
             null
          ]
       },
       "SAINT_HYACINTHE":{
          "id":1700151
       },
       "SAINT_JEAN_SUR_RICHELIEU":{
          "id":1700252
       },
       "SEPT_ILES":{
          "id":1700071
       },
       "SHERBROOKE":{
          "id":1700156
       }
    },
    "SASKATCHEWAN":{
       "id":9009,
       "LA_RONGE":{
          "id":1700265
       },
       "MEADOW_LAKE":{
          "id":1700264
       },
       "NIPAWIN":{
          "id":1700266
       },
       "PRINCE_ALBERT":{
          "id":1700088
       },
       "REGINA_AREA":{
          "id":1700194,
          "MOOSE_JAW":[
             null
          ],
          "REGINA":[
             null
          ]
       },
       "SASKATOON":{
          "id":1700197
       },
       "SWIFT_CURRENT":{
          "id":1700093
       }
    },
    
    "TERRITORIES":{
       "id":9010,
       "NORTHWEST_TERRITORIES":{
          "id":1700103,
          "YELLOWKNIFE":[
             null
          ]
       },
       "NUNAVUT":{
          "id":1700105,
          "IQALUIT":[
             null
          ]
       },
       "YUKON":{
          "id":1700101,
          "WHITEHORSE":[
             null
          ]
       }
    }
 }`